
        // //let variable
        // let a=26
        // console.log(a);

        // {
        //     let b=29 //didn't run because this is a block code
        // }
        // console.log(b);

        // //var variable
        // {
        //     var b=29 //this will give the output because this is a block code with var keyword.
        // }
        // console.log(b);

        // //const variable

        // const name="Muskan"
        // console.log(name);


        // name="Chaurasiya"//error because const is not reasinged
        // console.log(name);







    

    